In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import warnings

In [4]:
import matplotlib.pyplot as plt

In [5]:
import numpy as np

In [6]:
import sklearn

In [7]:
os.getcwd()

'/Users/samerens/Documents/GitHub/gsod-analysis/code'

In [8]:
os.listdir()

['Untitled1.ipynb',
 '.DS_Store',
 'data_cleaning.ipynb',
 'Untitled.ipynb',
 'gzip_pal.py',
 'data_agg.py',
 'gsod-analysis-part-2.ipynb',
 '.ipynb_checkpoints',
 'gsod-analysis-part-1.ipynb']

In [9]:
datapath = '/Users/samerens/Downloads/Weather Data/'

In [10]:
os.listdir(datapath)

['2004weatherdataclean.csv',
 '2019weatherdataclean.csv',
 '2000weatherdataclean.csv',
 '2018weatherdataclean.csv',
 '2002weatherdataclean.csv',
 '2003weatherdataclean.csv',
 '2017weatherdataclean.csv',
 '2016weatherdataclean.csv',
 '2015weatherdataclean.csv',
 '2014weatherdataclean.csv',
 '2012weatherdataclean.csv',
 '2013weatherdataclean.csv',
 '2010weatherdataclean.csv',
 '2009weatherdataclean.csv',
 '2011weatherdataclean.csv',
 '2008weatherdataclean.csv']

In [11]:
df = pd.DataFrame()

In [12]:
for file in os.listdir(datapath): df = pd.concat([df, pd.read_csv(datapath + file)])

In [13]:
len(os.listdir(datapath))

16

In [14]:
df.size

595436198

In [15]:
df.shape

(42531157, 14)

In [16]:
len(df)

42531157

In [17]:
df

station_num  temp_ft  year  month  day  fog  rain  snow  hail  \
0              10590     10.1  2004      1    1    0     0     0     0   
1              10590      8.0  2004      1    2    0     0     0     0   
2              10590     -2.0  2004      1    3    0     0     0     0   
3              10590      1.3  2004      1    4    0     0     0     0   
4              10590      0.4  2004      1    5    0     0     0     0   
...              ...      ...   ...    ...  ...  ...   ...   ...   ...   
2886177       350850    -14.2  2008     12   26    0     0     0     0   
2886178       350850     -4.6  2008     12   28    1     0     0     0   
2886179       350850      6.8  2008     12   29    1     0     0     0   
2886180       350850      0.6  2008     12   30    0     0     0     0   
2886181       350850      1.7  2008     12   31    0     0     0     0   

         thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
0              0        0        0.0            23.7             8.6  
1              0        0        0.0            13.1             3.2  
2              0        0        0.0             3.2            -5.8  
3              0        0        0.0             3.2            -2.0  
4              0        0        0.0             0.0            -4.2  
...          ...      ...        ...             ...             ...  
2886177        0        0        0.0            -3.3           -21.3  
2886178        0        0        0.0             8.6             0.0  
2886179        0        0        0.0            15.8             0.0  
2886180        0        0        0.0             6.8            -3.8  
2886181        0        0        0.0             5.5            -6.2  

[42531157 rows x 14 columns]

In [18]:
df.dtypes

station_num         int64
temp_ft           float64
year                int64
month               int64
day                 int64
fog                 int64
rain                int64
snow                int64
hail                int64
thunder             int64
tornado             int64
precip_in         float64
max_temp_frnht    float64
min_temp_frnht    float64
dtype: object

In [19]:
df.columns

Index(['station_num', 'temp_ft', 'year', 'month', 'day', 'fog', 'rain', 'snow',
       'hail', 'thunder', 'tornado', 'precip_in', 'max_temp_frnht',
       'min_temp_frnht'],
      dtype='object')

In [20]:
df.to_csv('/Users/samerens/Downloads/weather_data.csv', index = False)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
df['year'].unique()

array([2004, 2019, 2000, 2018, 2002, 2003, 2017, 2016, 2015, 2014, 2012,
       2013, 2010, 2009, 2011, 2008])

In [25]:
len(df['year'].unique())

16

In [26]:
sorted(df['year'].unique())

[2000,
 2002,
 2003,
 2004,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019]

In [27]:
test_df = df[df['year'] > 2016]

In [28]:
train_df = df[df['year'] < 2017]

In [29]:
len(train_df)

35932564

In [30]:
len(test_df)

6598593

In [31]:
len(train_df) / len(test_df)

5.4454887579821944

In [32]:
len(test_df) / len(train_df)

0.1836382452418369

In [33]:
len(train_df) / (len(train_df) + len(test_df))

0.8448527276133118

In [34]:
len(test_df) / (len(train_df) + len(test_df))

0.15514727238668818

In [35]:
train_x = train_df.drop('tornado', axis = 1)

In [36]:
train_y = train_df['tornado']

In [37]:
model = LogisticRegression()

In [38]:
model.fit(train_x, train_y)

LogisticRegression()

In [39]:
test_x = test_df.drop('tornado', axis = 1)

In [40]:
test_y = test_df['tornado']

In [41]:
predict = model.predict(test_x)

In [42]:
sum(df['tornado'])

579

In [43]:
sum(train_df['tornado'])

524

In [44]:
sum(test_df['tornado'])

55

In [45]:
help(accuracy_score)

Help on function accuracy_score in module sklearn.metrics._classification:

accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)
    Accuracy classification score.
    
    In multilabel classification, this function computes subset accuracy:
    the set of labels predicted for a sample must *exactly* match the
    corresponding set of labels in y_true.
    
    Read more in the :ref:`User Guide <accuracy_score>`.
    
    Parameters
    ----------
    y_true : 1d array-like, or label indicator array / sparse matrix
        Ground truth (correct) labels.
    
    y_pred : 1d array-like, or label indicator array / sparse matrix
        Predicted labels, as returned by a classifier.
    
    normalize : bool, default=True
        If ``False``, return the number of correctly classified samples.
        Otherwise, return the fraction of correctly classified samples.
    
    sample_weight : array-like of shape (n_samples,), default=None
        Sample weights.
    
    Ret

In [46]:
accuracy_score(y_true = test_y, y_pred = predict)

0.9999916648897728

In [47]:
sum(abs(predict - test_y))

55

In [48]:
sum(predict)

0

In [49]:
df['year'].min()

2000

In [50]:
df['year'].max()

2019

In [51]:
max(df['year'])

2019

In [52]:
min(df['year'])

2000

In [53]:
df['year'].unique()

array([2004, 2019, 2000, 2018, 2002, 2003, 2017, 2016, 2015, 2014, 2012,
       2013, 2010, 2009, 2011, 2008])

In [54]:
df['station_num']

0           10590
1           10590
2           10590
3           10590
4           10590
            ...  
2886177    350850
2886178    350850
2886179    350850
2886180    350850
2886181    350850
Name: station_num, Length: 42531157, dtype: int64

In [55]:
df['station_num'].unique()

array([ 10590, 700634, 714450, ..., 998215, 879360, 405690])

In [56]:
stations = list(df['station_num'].unique())

In [57]:
stations

[10590,
 700634,
 714450,
 489170,
 286660,
 389540,
 711620,
 724303,
 39650,
 23240,
 992230,
 702756,
 712250,
 723525,
 304050,
 702120,
 967830,
 121054,
 407270,
 403770,
 766560,
 839850,
 604170,
 106160,
 722526,
 724855,
 298220,
 994290,
 703810,
 951010,
 71100,
 261450,
 723415,
 646000,
 717230,
 763820,
 712510,
 946330,
 713510,
 430630,
 966550,
 478930,
 618110,
 645100,
 948630,
 476410,
 999999,
 996480,
 135770,
 946590,
 13670,
 852930,
 601900,
 312950,
 744104,
 276790,
 720302,
 724660,
 22450,
 946750,
 83300,
 110240,
 66210,
 111010,
 24490,
 485570,
 221130,
 724750,
 42660,
 33300,
 21350,
 896420,
 946010,
 325830,
 12280,
 722925,
 85520,
 407230,
 73850,
 722185,
 627330,
 62570,
 29580,
 307810,
 677610,
 292820,
 994086,
 920440,
 727535,
 969370,
 12710,
 401010,
 279470,
 442030,
 936150,
 725648,
 710680,
 994700,
 710560,
 471850,
 720322,
 646500,
 715860,
 171120,
 725320,
 25570,
 722145,
 164800,
 403620,
 471060,
 31350,
 330270,
 61560,
 128

In [58]:
station = stations[0]

In [59]:
station

10590

In [60]:
station_df = df[df['station_num'] == station]

In [61]:
station_df

station_num  temp_ft  year  month  day  fog  rain  snow  hail  \
0              10590     10.1  2004      1    1    0     0     0     0   
1              10590      8.0  2004      1    2    0     0     0     0   
2              10590     -2.0  2004      1    3    0     0     0     0   
3              10590      1.3  2004      1    4    0     0     0     0   
4              10590      0.4  2004      1    5    0     0     0     0   
...              ...      ...   ...    ...  ...  ...   ...   ...   ...   
2372812        10590     30.3  2008     12   27    1     0     0     0   
2372813        10590     43.8  2008     12   28    1     0     0     0   
2372814        10590     44.5  2008     12   29    1     0     0     0   
2372815        10590     33.6  2008     12   30    1     1     0     0   
2372816        10590     21.0  2008     12   31    1     0     0     0   

         thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
0              0        0       0.00            23.7             8.6  
1              0        0       0.00            13.1             3.2  
2              0        0       0.00             3.2            -5.8  
3              0        0       0.00             3.2            -2.0  
4              0        0       0.00             0.0            -4.2  
...          ...      ...        ...             ...             ...  
2372812        0        0       0.21            38.8            26.6  
2372813        0        0       0.02            50.0            31.1  
2372814        0        0       0.00            46.9            42.1  
2372815        0        0       0.13            45.3            23.0  
2372816        0        0       0.15            24.3            17.6  

[4666 rows x 14 columns]

In [62]:
sum(station_df['tornado'])

1

In [63]:
sum(station_df['precip_in'])

144.2400000000006

In [64]:
df_groupby = df.groupby('station_num').sum().reset_index()

In [65]:
df_groupby

station_num   temp_ft     year  month    day  fog  rain  snow  hail  \
0             7018    8694.7   233296    573   1907    0     0     0     0   
1             7026    1567.7    46328    185    434    4     0     0     0   
2             7070     150.1     4030     18     51    0     0     0     0   
3             8260   28676.9  1064971   2935   8411  453   206    30    61   
4             8268    2061.7    56307    188    436    0     0     0     0   
...            ...       ...      ...    ...    ...  ...   ...   ...   ...   
15486       998860    4367.0    90135    270    770    1     0     0     1   
15487       999100      63.5     2002      6     12    0     0     0     0   
15488       999110    6694.2   270270    435   1985   38     4     2     1   
15489       999120    6489.5   272272    446   2007   84    10     3     8   
15490       999999  208103.2  8151878  27431  63833  271    45     1     8   

       thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
0            0        0       0.00          9199.4          6152.8  
1            0        0       0.00          1676.4          1108.8  
2            0        0       0.00           179.2           134.2  
3           63        0     108.67         34459.3         19315.5  
4            0        0       0.00          2293.2          1502.4  
...        ...      ...        ...             ...             ...  
15486        0        0       0.00          4491.2          3583.8  
15487        0        0       0.00            68.0            57.2  
15488        0        0       5.15          7034.4          4872.4  
15489        2        0       4.28          7721.1          4127.3  
15490        0        0     229.44        223547.6        149465.1  

[15491 rows x 14 columns]

In [66]:
len(stations)

15491

In [67]:
df_groupby['tornado']

0        0
1        0
2        0
3        0
4        0
        ..
15486    0
15487    0
15488    0
15489    0
15490    0
Name: tornado, Length: 15491, dtype: int64

In [68]:
df_groupby[df_groupby['tornado'] > 0]

station_num   temp_ft      year  month    day   fog  rain  snow  hail  \
30           10280  159621.5  10001047  32117  78003  4511  1880   365    11   
45           10520  186212.7  10077685  32327  78527  3281   842    57    14   
48           10590  164838.8   9377868  30030  73365  3072   473    42    21   
76           10980  147150.2   8009380  25555  62833  2336   406    99    11   
77           10990   94636.4   5355314  17054  41438  1311   124    19     4   
...            ...       ...       ...    ...    ...   ...   ...   ...   ...   
14533       965250  351005.1   8537300  27678  66985  1853    24    39   516   
14538       965650  362780.7   8767125  28349  68065  2086    37     2   327   
14547       966450  288942.3   7247935  23383  56495  2183   180     3   733   
14634       977895     115.6      6012     21     42     3     0     0     0   
14698       987510  398113.9  10625315  34065  82896  3006   452     2   283   

       thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
30           7        2     252.39        156277.6        124049.5  
45           2        2     258.12        184216.3        146559.7  
48           4        1     144.24        172634.7        117695.2  
76           2        1     227.18        144628.3        118572.5  
77           1        2       0.00         91859.1         74322.2  
...        ...      ...        ...             ...             ...  
14533        7        1     532.73        349390.8        317148.8  
14538       24        1     553.02        357360.1        320108.8  
14547      175        1     805.31        291927.2        260165.0  
14634        0        1       0.00            89.2           101.4  
14698       62        1    1584.79        406096.7        320925.6  

[436 rows x 14 columns]

In [69]:
df_groupby[df_groupby['tornado'] == max(df_groupby['tornado'])]

station_num   temp_ft     year  month    day   fog  rain  snow  hail  \
10180       722010  347441.2  8921048  28979  69847  1691   221     1   411   

       thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
10180      167       14     486.61        319935.9        285669.1

In [70]:
df2 = df[df['station_num'] == 722010]

In [71]:
df2

station_num  temp_ft  year  month  day  fog  rain  snow  hail  \
1742605       722010     73.1  2004      1    1    1     1     0     0   
1742606       722010     73.2  2004      1    2    1     0     0     0   
1742607       722010     73.2  2004      1    3    1     0     0     0   
1742608       722010     74.8  2004      1    4    1     0     0     0   
1742609       722010     75.2  2004      1    5    0     0     0     0   
...              ...      ...   ...    ...  ...  ...   ...   ...   ...   
595133        722010     74.3  2008     12   26    1     0     0     0   
595134        722010     74.4  2008     12   27    0     0     0     0   
595135        722010     74.7  2008     12   28    0     0     0     0   
595136        722010     73.9  2008     12   29    0     0     0     0   
595137        722010     71.1  2008     12   30    0     0     0     0   

         thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
1742605        0        0       0.01             0.0             0.0  
1742606        0        0       0.01             0.0             0.0  
1742607        0        0       0.08            78.1             0.0  
1742608        0        0       0.01             0.0            70.0  
1742609        0        0       0.00            80.1            73.0  
...          ...      ...        ...             ...             ...  
595133         0        0       0.03            80.1            71.1  
595134         0        0       0.06            77.0            72.0  
595135         0        0       0.00            78.1            73.0  
595136         0        0       0.00             0.0            68.0  
595137         0        0       0.00             0.0            68.0  

[4440 rows x 14 columns]

In [72]:
df2['tornado'].unique()

array([0, 1])

In [73]:
sum(df2['precip_in']) / 16

30.413124999999887

In [74]:
df2['precip_in'].unique()

array([0.01, 0.08, 0.  , 0.06, 0.03, 0.48, 0.24, 1.02, 0.73, 0.02, 0.04,
       0.05, 1.93, 0.07, 1.05, 0.39, 0.26, 0.75, 1.83, 0.17, 0.09, 0.37,
       1.52, 0.13, 0.36, 0.46, 0.78, 0.12, 0.44, 0.59, 0.68, 1.23, 0.19,
       0.11, 1.18, 0.35, 0.18, 0.14, 0.33, 0.76, 0.94, 0.3 , 0.28, 1.11,
       0.25, 0.7 , 0.65, 0.38, 0.21, 0.23, 0.27, 0.29, 1.34, 0.22, 0.2 ,
       1.1 , 1.95, 0.53, 1.06, 0.1 , 0.69, 0.6 , 0.15, 2.4 , 0.63, 0.62,
       0.79, 0.45, 0.32, 0.51, 0.41, 1.14, 0.83, 0.74, 3.32, 1.79, 0.4 ,
       1.12, 1.99, 1.67, 0.56, 2.12, 1.92, 0.9 , 1.5 , 2.41, 2.75, 0.43,
       1.32, 1.07, 3.41, 1.62, 0.71, 0.47, 0.58, 3.51, 1.16, 1.28, 0.49,
       0.99, 0.84, 3.37, 0.16, 1.42, 0.91, 0.42, 0.55, 1.2 , 0.31, 0.72,
       0.54, 2.13, 1.09, 1.9 , 1.55, 0.34, 4.23, 0.89, 0.64, 0.52, 0.81,
       1.15, 0.5 , 2.56, 2.45, 1.01, 1.17, 0.85, 0.66, 0.61, 5.28, 0.96,
       1.29, 3.14, 0.77, 1.49, 1.08, 3.04, 4.56, 1.41, 2.47, 3.31, 1.66,
       1.04, 0.97, 1.45, 0.82, 1.13, 1.39, 1.03, 4.

In [75]:
max(df2['precip_in'])

7.0

In [76]:
df2['station_num'].unique()

array([722010])

In [77]:
df2.groupby('year').sum()

station_num  temp_ft  month   day  fog  rain  snow  hail  thunder  \
year                                                                      
2000    251981490  27082.4   2290  5576  146    38     1    49       36   
2002    241873350  26283.9   2219  5184  142    46     0    22       35   
2003    247649430  26914.9   2238  5410  144    37     0    29       18   
2004    244761390  26280.6   2189  5279  141    34     0    22       21   
2008    242595360  26246.8   2168  5246  114     8     0    32       10   
2009    242595360  26352.7   2167  5310  124     8     0    38       13   
2010    249093450  26296.5   2248  5462  135    10     0    25        8   
2011    244039380  26542.5   2243  5307  112     2     0    25        0   
2012    249815460  26866.9   2261  5454  119     5     0    15        2   
2013    242595360  26391.8   2197  5263  120    10     0    14        5   
2015    249093450  27557.8   2235  5403  126     8     0    46        5   
2016    249815460  27191.6   2288  5492  138     8     0    54        9   
2017    249815460  27432.8   2236  5461  130     7     0    40        5   

      tornado  precip_in  max_temp_frnht  min_temp_frnht  
year                                                      
2000        8      33.20         22867.4         22324.6  
2002        3      42.35         24753.7         20310.8  
2003        1      37.50         24483.3         21569.9  
2004        0      31.19         24406.1         21888.1  
2008        2      37.50         23251.1         21586.5  
2009        0      32.98         25773.0         22151.5  
2010        0      39.56         23622.1         21069.4  
2011        0      38.33         23633.8         21685.9  
2012        0      42.28         24800.9         22090.7  
2013        0      45.90         23844.3         22255.8  
2015        0      37.30         27038.8         23116.8  
2016        0      37.15         25464.9         23525.1  
2017        0      31.37         25996.5         22094.0

In [78]:
train_df2 = df2[df2['year'] < 2004]

In [79]:
test_df2 = df2[df2['year'] == 2008]

In [80]:
train_x = train_df2.drop('tornado', axis = 1)

In [81]:
train_y = train_df2['tornado']

In [82]:
model2 = LogisticRegression()

In [83]:
model2.fit(train_x, train_y)

LogisticRegression()

In [84]:
test_x = test_df2.drop('tornado', axis = 1)

In [85]:
test_y = test_df2['tornado']

In [86]:
predict = model2.predict(test_x)

In [87]:
accuracy_score(y_true = test_y, y_pred = predict)

0.9940476190476191

In [88]:
sum(predict)

0

In [89]:
sum(train_df2['tornado'])

12

In [90]:
sum(test_df2['tornado'])

2

In [91]:
len(train_df2)

1027

In [92]:
len(test_df2)

336

In [93]:
df

station_num  temp_ft  year  month  day  fog  rain  snow  hail  \
0              10590     10.1  2004      1    1    0     0     0     0   
1              10590      8.0  2004      1    2    0     0     0     0   
2              10590     -2.0  2004      1    3    0     0     0     0   
3              10590      1.3  2004      1    4    0     0     0     0   
4              10590      0.4  2004      1    5    0     0     0     0   
...              ...      ...   ...    ...  ...  ...   ...   ...   ...   
2886177       350850    -14.2  2008     12   26    0     0     0     0   
2886178       350850     -4.6  2008     12   28    1     0     0     0   
2886179       350850      6.8  2008     12   29    1     0     0     0   
2886180       350850      0.6  2008     12   30    0     0     0     0   
2886181       350850      1.7  2008     12   31    0     0     0     0   

         thunder  tornado  precip_in  max_temp_frnht  min_temp_frnht  
0              0        0        0.0            23.7             8.6  
1              0        0        0.0            13.1             3.2  
2              0        0        0.0             3.2            -5.8  
3              0        0        0.0             3.2            -2.0  
4              0        0        0.0             0.0            -4.2  
...          ...      ...        ...             ...             ...  
2886177        0        0        0.0            -3.3           -21.3  
2886178        0        0        0.0             8.6             0.0  
2886179        0        0        0.0            15.8             0.0  
2886180        0        0        0.0             6.8            -3.8  
2886181        0        0        0.0             5.5            -6.2  

[42531157 rows x 14 columns]

In [94]:
len(df)

42531157

In [95]:
df3 = df.drop(['month', 'day'], axis = 1)

In [96]:
df3 = df.groupby(['station_num', 'year']).agg({
    'temp_ft': np.mean,
    'fog': np.sum,
    'rain': np.sum,
    'snow': np.sum,
    'hail': np.sum,
    'thunder': np.sum,
    'tornado': np.sum,
    'precip_in': np.sum,
    'max_temp_frnht': np.max,
    'min_temp_frnht': np.min
}).reset_index()

In [97]:
df3

station_num  year    temp_ft  fog  rain  snow  hail  thunder  tornado  \
0              7018  2011  74.402830    0     0     0     0        0        0   
1              7018  2013  80.800000    0     0     0     0        0        0   
2              7026  2012  83.180000    0     0     0     0        0        0   
3              7026  2014  49.410000    2     0     0     0        0        0   
4              7026  2016  82.212500    2     0     0     0        0        0   
...             ...   ...        ...  ...   ...   ...   ...      ...      ...   
152625       999999  2015  60.502795    0     0     0     0        0        0   
152626       999999  2016  64.506811    0     0     0     0        0        0   
152627       999999  2017  55.360366    0     0     0     0        0        0   
152628       999999  2018  46.184356  185    33     1     8        0        0   
152629       999999  2019  31.235714    0     0     0     0        0        0   

        precip_in  max_temp_frnht  min_temp_frnht  
0            0.00           116.6             0.0  
1            0.00           102.2             0.0  
2            0.00           107.6            71.6  
3            0.00            84.2             0.0  
4            0.00           100.4             0.0  
...           ...             ...             ...  
152625       9.70            98.6             0.0  
152626      50.09            98.8             0.0  
152627      43.90            90.3             0.0  
152628       0.00            93.0           -18.8  
152629       4.62            50.9           -20.9  

[152630 rows x 12 columns]

In [98]:
df4 = df3[df3['station_num'] == 722010]

In [99]:
df4

station_num  year    temp_ft  fog  rain  snow  hail  thunder  tornado  \
102747       722010  2000  77.600000  146    38     1    49       36        8   
102748       722010  2002  78.459403  142    46     0    22       35        3   
102749       722010  2003  78.469096  144    37     0    29       18        1   
102750       722010  2004  77.523894  141    34     0    22       21        0   
102751       722010  2008  78.115476  114     8     0    32       10        2   
102752       722010  2009  78.430655  124     8     0    38       13        0   
102753       722010  2010  76.221739  135    10     0    25        8        0   
102754       722010  2011  78.528107  112     2     0    25        0        0   
102755       722010  2012  77.650000  119     5     0    15        2        0   
102756       722010  2013  78.547024  120    10     0    14        5        0   
102757       722010  2015  79.877681  126     8     0    46        5        0   
102758       722010  2016  78.588439  138     8     0    54        9        0   
102759       722010  2017  79.285549  130     7     0    40        5        0   

        precip_in  max_temp_frnht  min_temp_frnht  
102747      33.20            93.0             0.0  
102748      42.35            93.0             0.0  
102749      37.50            93.0             0.0  
102750      31.19            91.0             0.0  
102751      37.50            91.9             0.0  
102752      32.98            96.1             0.0  
102753      39.56            96.1             0.0  
102754      38.33            93.0             0.0  
102755      42.28            90.0             0.0  
102756      45.90            91.0             0.0  
102757      37.30            95.0             0.0  
102758      37.15            93.0             0.0  
102759      31.37            93.9             0.0

In [100]:
model = LogisticRegression()

In [101]:
train_df = df4[df4['year'] < 2015]

In [102]:
test_df = df4[df4['year'] >= 2015]

In [103]:
train_x = train_df.drop('tornado', axis = 1)

In [104]:
train_y = train_df['tornado']

In [105]:
test_x = test_df.drop('tornado', axis = 1)

In [106]:
test_y = test_df['tornado']

In [107]:
model.fit(train_x, train_y)

LogisticRegression()

In [108]:
predict = model.predict(test_x)

In [109]:
sum(predict)

0

In [110]:
predict

array([0, 0, 0])

In [111]:
test_x

station_num  year    temp_ft  fog  rain  snow  hail  thunder  \
102757       722010  2015  79.877681  126     8     0    46        5   
102758       722010  2016  78.588439  138     8     0    54        9   
102759       722010  2017  79.285549  130     7     0    40        5   

        precip_in  max_temp_frnht  min_temp_frnht  
102757      37.30            95.0             0.0  
102758      37.15            93.0             0.0  
102759      31.37            93.9             0.0

In [112]:
accuracy_score(y_true = test_y, y_pred = predict)

1.0

In [113]:
warnings.filterwarnings(action = 'ignore')

stations = []
scores = []

for station in df3['station_num'].unique():
    
    try:
        
        sample_df = df[df['station_num'] == station]

        train_df, test_df = train_test_split(sample_df)

        train_x = train_df.drop('tornado', axis = 1)
        train_y = train_df['tornado']

        test_x = test_df.drop('tornado', axis = 1)
        test_y = test_df['tornado']

        model = LogisticRegression()
        model.fit(train_x, train_y)
        
        predict = model.predict(test_x)

        score = accuracy_score(y_true = test_y, y_pred = predict)

        stations.append(station)
        scores.append(score)
        
    except: continue
    
output_df = pd.DataFrame({'station': stations, 'score': score})
output_df.to_csv('/Users/samerens/Downloads/tornado_scores.csv', index = False)

In [114]:
import warnings

In [115]:
output_df

station  score
0      10280    1.0
1      10520    1.0
2      10590    1.0
3      10990    1.0
4      11390    1.0
..       ...    ...
344   947760    1.0
345   965250    1.0
346   965650    1.0
347   966450    1.0
348   987510    1.0

[349 rows x 2 columns]

In [116]:
output_df['score']

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
344    1.0
345    1.0
346    1.0
347    1.0
348    1.0
Name: score, Length: 349, dtype: float64

In [117]:
np.mean(output_df['score'])

1.0